/*
============================================
; Title: VerifySecurityQuestionsFormComponent
; Author: Professor Krasso
; Date:   21 Apr 2021
; Modified by:
;===========================================
*/
// This was autogenerated
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-verify-security-questions-form',
  templateUrl: './verify-security-questions-form.component.html',
  styleUrls: ['./verify-security-questions-form.component.css']
})
export class VerifySecurityQuestionsFormComponent implements OnInit {
  /**
   * Variables
   */

  constructor() { }

  ngOnInit(): void {
  }

}
