/*
============================================
; Title: VerifySecurityQuestionsFormComponent
; Author: Professor Krasso
; Date:   21 Apr 2021
; Modified by:
;===========================================
*/
// This was autogenerated
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
// Imported
import { HttpClient } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ISecurityQuestion } from '../../shared/security-question.interface';

@Component({
  selector: 'app-verify-security-questions-form',
  templateUrl: './verify-security-questions-form.component.html',
  styleUrls: ['./verify-security-questions-form.component.css']
})
export class VerifySecurityQuestionsFormComponent implements OnInit {
  /**
   * Variables
   */
  selectedSecurityQuestions: ISecurityQuestion[];
  username: string;

  constructor(private route: ActivatedRoute, private router: Router, private http: HttpClient, private fb: FormBuilder) {
    // Username
    this.username = this.route.snapshot.queryParamMap.get('username');
    console.log(this.username);

   }

  ngOnInit(): void {
  }

  /**
   * Verify Security Questions
   */
}
