/*
============================================
; Title: security-question interface file
; Author: Professor Krasso
; Date:   16 Apr 2021
; Modified by: Devan Wong
; Description: security-question interface page
;===========================================
*/
// This was autogenerated
import { Injectable } from '@angular/core';
// Imported security question interface.
import { SecurityQuestion } from "./security-question.interface";
import { HttpClient } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SecurityQuestionService {

  constructor(private http: HttpClient) { }


  /*
    findAllSecurity API : Devan
  */
  findAllSecurityQuestions(): Observable<any> {
    return this.http.get('/api/security-questions/' + questionId);
  }

  /*
    findSecurityById API : Erica
  */




  /*
    CreateSecurityQuestion API: Anil
  */






  /*
    UpdateSecurityQuestions API : Devan
  */
  updateSecurityQuestion(questionId: string, updateSecurityQuestion: SecurityQuestion): Observable<any> {
    return this.http.put('/api/security-questions/' + questionId, {
      text: updatedSecurityQuestion.text
    })
  }

  /*
    DeleteSecurityQuestions API : Erica
  */


  /*
    FindSecurityQuestionsByIds API: Sprint 2
  */


}
