/*
============================================
; Title: user service TS file
; Author: Professor Krasso
; Date:   16 Apr 2021
; Modified by: Devan Wong
; Description: User.service.ts file
;===========================================
*/
// This was autogenerated.
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor() { }
}
