/*
============================================
; Title: user service TS file
; Author: Professor Krasso
; Date:   16 Apr 2021
; Modified by: Devan Wong
; Description: User.service.ts file
;===========================================
*/
// This was autogenerated.
import { Injectable } from '@angular/core';
import { User } from './user.interface';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';


@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private http: HttpClient) { }

  /*
    findAllUser API
  */
  findAllUsers(): Observable<any> {
    return this.http.get('/api/users');
  }

  /*
    findUserbyId API : Anil
  */

   /*
    createUser API : Anil
  */

   /*
    updateUser API
  */
  updateUser(userId: string, user: User): Observable<any> {
    return this.http.put('api/users/' + userId, {
      firstName: user.firstName,
      lastName: user.lastName,
      phoneNumber: user.phoneNumber,
      address: user.address,
      email: user.email
    });
  }
   /*
    deleteUser API : Erica
  */

}
