/*
============================================
; Title: User-create components
; Author: Professor Krasso
; Date:   17 Apr 2021
; Modified by:
; Description: User-creates component.ts
;===========================================
*/

// This is autogenerated.
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-user-create',
  templateUrl: './user-create.component.html',
  styleUrls: ['./user-create.component.css']
})
export class UserCreateComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
