/*
============================================
; Title: Signin.ts
; Author: Professor Krasso
; Date:   17 Apr 2021
; Modified by: Devan Wong
; Description: This is the signin.component.ts
;===========================================
*/

// This was autogenerated/
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css']
})
export class SigninComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
